- name: Atom
  hosts: IOTLP
  become: true
  tasks:
   - name: Update and upgrade apt packages
     apt:
      update_cache: yes
      upgrade: yes

   - name: Add Atom Repository
     apt_repository:
      repo: ppa:webupd8team/atom
      state: present
      filename: atom
      
   - name: Install Atom Editor
     apt:
      name: atom
      state: present
      update_cache: yes