- name: ESP32
  hosts: IOTLP
  become: true
  tasks:
   - name: Install prerequisites
     apt:
      name:
       - git
       - wget
       - flex
       - bison
       - gperf
       - python3
       - python3-pip
       - python3-venv
       - cmake
       - ninja-build
       - ccache
       - libffi-dev
       - libssl-dev
       - dfu-util
       - libusb-1.0-0
       state: present
   - name: Create directory for ESP-IDF
     file:
      path: "~/esp"
      state: directory
   - name: Clone ESP-IDF repository
     git:
      repo: "https://github.com/espressif/esp-idf.git"
      dest: "~/esp/esp-idf"
      recursive: yes
   - name: Run the install script
     command: "~/esp/esp-idf/install.sh all"
