- name: Atom
  hosts: IOTLP
  become: true
  tasks:
   - name: Update and upgrade apt packages
     apt:
      update_cache: yes
      upgrade: yes
      
   - name: Install Atom Editor
     command: snap install atom --classic