- name: Big boy
  hosts: all
  become: yes
  tasks:
   - name: Debug
     debug:
       msg: big play
- name: Execute Packages Play
  import_playbook: Packages_playbook.yml
  
- name: Execute Crome
  import_playbook: Chrome_playbook.yml
  
- name: Execute Java
  import_playbook: Java_Playbook.yml
  
- name: Execute Visual Studio Code
  import_playbook: Vscode_playbook.yml
  
- name: Execute Visual Studio Code Extentions
  import_playbook: VsCode_extentions_playbook.yml
  
- name: Execute Atom
  import_playbook: Atom_playbook.yml
  
- name: Execute Arduino
  import_playbook: Arduino_playbook.yml
  
- name: Execute ESP32
  import_playbook: ESP32_playbook.yml
