- name: Vscode
  hosts: IOTLP
  become: true
  tasks:
   - name: Install wget and gpg
     apt:
      name:
       - wget
       - gpg
      state: present

   - name: Download Microsoft's GPG key
     get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: /tmp/packages.microsoft.gpg

   - name: Import Microsoft's GPG key
     command: gpg --dearmor -o /etc/apt/trusted.gpg.d/packages.microsoft.gpg /tmp/packages.microsoft.gpg

   - name: Install Microsoft's GPG key
     copy:
      src: /tmp/packages.microsoft.gpg
      dest: /etc/apt/keyrings/packages.microsoft.gpg
      owner: root
      group: root
      mode: '0644'
      remote_src: yes

   - name: Add the Visual Studio Code repository
     apt_repository:
      repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
      state: present
      filename: vscode

   - name: Update the package list
     apt:
      update_cache: yes

   - name: Clean up
     file:
      path: /tmp/packages.microsoft.gpg
      state: absent

   - name: apt-transport-https
     apt:
      name: apt-transport-https
      state: latest
      update_cache: yes

   - name: Install Visual Studio Code
     apt:
      name: code
      state: present