- name: Arduino
  hosts: IOTLP
  tasks:
   - name: Enshure /programs folder exists
     file:
      path: "~/programs/"
      state: directory

   - name: Download Arduino IDE
     get_url:
      url: "https://downloads.arduino.cc/arduino-1.8.5-linux64.tar.xz"
      dest: "~/Downloads/arduino-1.8.5-linux64.tar.xz"

   - name: Extract the tar file
     unarchive:
      src: "~/Downloads/arduino-1.8.5-linux64.tar.xz"
      dest: "~/programs/"
      remote_src: yes

   - name: Run the install script
     command: "~/programs/arduino-1.8.5/install.sh"
