- name: Java
  hosts: all
  become: yes
  tasks:

   - name: Update apt cache
     apt:
      update_cache: yes

   - name: Reinstall Oracle Java 8
     apt:
      name: openjdk-8-jdk
      state: present

   - name: Check Java version
     command: java -version
     register: java_version
     changed_when: false

   - name: Print Java version
     debug:
      msg: "{{ java_version.stdout_lines }}"
