---
- name: Enable SSH Password Authentication
  hosts: iotrp
  become: yes
  tasks:
    - name: Ensure SSH is installed
      apt:
        name: openssh-server
        state: present

    - name: Backup the current sshd_config file
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        remote_src: yes
        backup: yes

    - name: Enable SSH Password Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
